---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${MOLECULE_DISTRO:-ubuntu:bionic}

provisioner:
  name: ansible
  env:
    HELM_VERSION: "3.8.0"

verifier:
  name: ansible