---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${MOLECULE_DISTRO:-ubuntu:bionic}

provisioner:
  name: ansible
  playbooks:
    prepare: ../specific-version/converge.yml
    converge: converge.yml
  env:
    HELM_VERSION: "3.9.0"

verifier:
  name: ansible
